# Generated by Django 5.2.1 on 2025-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('freemium_user', 'Freemium User')], default='freemium_user', help_text="User's role in the application", max_length=20),
        ),
    ]
