# Generated by Django 5.2.1 on 2025-07-07 08:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_party_id', models.CharField(max_length=255)),
                ('third_party_type', models.CharField(max_length=255)),
                ('title', models.CharField()),
                ('content', models.TextField()),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list), size=None)),
                ('probability', models.FloatField()),
                ('places', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scraping.scrapedplace')),
            ],
        ),
    ]
