# Generated by Django 5.2.1 on 2025-07-07 09:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedplace',
            name='type',
        ),
        migrations.RemoveField(
            model_name='scrapedpost',
            name='places',
        ),
        migrations.AddField(
            model_name='scrapedplace',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='scraping.scrapedpost'),
        ),
        migrations.AddField(
            model_name='scrapedplace',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='scrapedpost',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=list), size=None),
        ),
        migrations.AlterField(
            model_name='scrapedpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
