# Generated by Django 5.2.1 on 2025-07-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_remove_scrapedplace_type_remove_scrapedpost_places_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedplace',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
