# Generated by Django 5.2.1 on 2025-07-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_scrapedplace_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedplace',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
