# Generated by Django 5.2.1 on 2025-07-08 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_scrapedplace_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapedpost',
            name='original_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapedpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
