# Generated by Django 5.2.1 on 2025-07-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_scrapedpost_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedplace',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scraping.scrapedpost'),
        ),
    ]
