# Generated by Django 5.2.1 on 2025-06-04 13:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('google_maps_url', models.URLField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('INDOOR_PLAYGROUND', 'Indoor Playground'), ('PLAYGROUND', 'Playground'), ('RESTAURANT', 'Restaurant'), ('RECURRING_ACTIVITY', 'Recurring Activity'), ('EVENT', 'Event'), ('CAFE', 'Cafe'), ('KINDERGARTEN', 'Kindergarten')], max_length=255)),
            ],
        ),
    ]
