# Generated by Django 5.2.1 on 2025-07-07 14:25

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0003_scrapedplace_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PLAYGROUND', 'Playground'), ('INDOOR_PLAYGROUND', 'Indoor Playground'), ('KINDERGARTEN', 'Kindergarten'), ('CAFE', 'Cafe'), ('RESTAURANT', 'Restaurant'), ('SHOP', 'Shop'), ('AMUSEMENT_PARK', 'Amusement Park'), ('MUSEUM', 'Museum'), ('GALLERY', 'Gallery'), ('ZOO', 'Zoo'), ('AQUAPARK', 'Aquapark'), ('COMMUNITY_CENTER', 'Community Center'), ('KIDS_PLAYROOM', 'Kids Playroom'), ('CASTLE', 'Castle'), ('HOTEL', 'Hotel'), ('ATTRACTION', 'Attraction'), ('NATURAL_ATTRACTION', 'Natural Attraction')], max_length=255), db_index=True, default=list, size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('country_code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('season', models.CharField(blank=True, choices=[('WINTER', 'Winter'), ('SUMMER', 'Summer'), ('ALL', 'All')], max_length=255, null=True)),
                ('is_admission_free', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('scraped_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.scrapedplace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
