# Generated by Django 5.2.1 on 2025-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('INDOOR_PLAYGROUND', 'Indoor Playground'), ('PLAYGROUND', 'Playground'), ('RESTAURANT', 'Restaurant'), ('FAMILY_SPOT', 'Family Spot'), ('CAFE', 'Cafe'), ('KINDERGARTEN', 'Kindergarten')], max_length=255),
        ),
    ]
