# Generated by Django 5.2.1 on 2025-05-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lat',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='place',
            name='lon',
        ),
    ]
