# Generated by Django 5.2.1 on 2025-07-08 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_street_place_zip_code_and_more'),
        ('scraping', '0005_scrapedpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='scraped_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='scraping.scrapedplace'),
        ),
    ]
