# Generated by Django 5.2.1 on 2025-07-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_place_scraped_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='car_needed',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
