# Generated by Django 5.2.1 on 2025-07-09 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_place_car_needed'),
        ('scraping', '0008_alter_scrapedplace_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='scraped_id_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='scraping.scrapedpost'),
        ),
        migrations.AlterField(
            model_name='place',
            name='scraped_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='scraping.scrapedplace'),
        ),
    ]
