# Generated by Django 5.2.1 on 2025-07-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_place_scraped_id_2_alter_place_scraped_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='scraped_id',
        ),
    ]
