# Generated by Django 5.2.1 on 2025-07-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_remove_place_scraped_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='scraped_id_2',
            new_name='scraped_id',
        ),
    ]
